=== franklin-maduabueke/NewsCMS/sports/football/template.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">

	<xs:simpleType name="sectionHeading">
		<xs:restriction base="xs:string">
			<xs:maxLength value="40" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="subcategoryID">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9_]{8}" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="GroupType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9_]{10}" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="heading" type="sectionHeading" />
				<xs:element name="subcategoryLink" type="subcategoryID"/>
				<xs:element name="articleGroup" type="GroupType" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sections">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="section" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="looknfeelClass">
		<xs:sequence>
			<xs:element name="sections"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:element name="templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="looknfeel" type="looknfeelClass" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== franklin-maduabueke/NewsCMS/life_and_style/asia/asia.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<templates xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com template.xsd"><looknfeel id="lifeAndStyleSubcatLook">
		<sections>
			<section id="s1">
				<heading/>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
			
			<section id="s2">
				<heading/>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
			
			<section id="s3">
				<heading/>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
			
			<section id="s4">
				<heading/>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
			
			<section id="s5">
				<heading/>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
			
			<section id="s6">
				<heading/>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
			
			<section id="s7">
				<heading/>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
		</sections>
	</looknfeel></templates>

=== franklin-maduabueke/NewsCMS/life_and_style/life_and_style.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<templates xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com template.xsd"><looknfeel id="lifeAndStyleLook">
		<sections>
			<section id="s1">
				<heading>Fashion &amp; Style</heading>
			
				<subcategoryLink>QRo5SSHc</subcategoryLink>
			</section>
			
			<section id="s2">
				<heading>Food &amp; Drinks</heading>
			
				<subcategoryLink>kleAWDdR</subcategoryLink>
			</section>
			
			<section id="s3">
				<heading>Africa</heading>
			
				<subcategoryLink>4fgrkFh_</subcategoryLink>
			</section>
			
			<section id="s4">
				<heading>America</heading>
			
				<subcategoryLink>Pc1_SVp3</subcategoryLink>
			</section>
			
			<section id="s5">
				<heading>Europe</heading>
			
				<subcategoryLink>bPmTU0wy</subcategoryLink>
			</section>
			
			<section id="s6">
				<heading>Asia</heading>
			
				<subcategoryLink>51EI___F</subcategoryLink>
			</section>
			
			<section id="s7">
				<heading>more from fashion &amp; style  around the world</heading>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
		</sections>
	</looknfeel></templates>

=== franklin-maduabueke/NewsCMS/xmls/template.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<templates xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com template.xsd"
>
<!-- *******************************************************************************
USERS WILL NOT BE ABLE TO SELECT THIS TEMPLATE WHEN CREATING CATEGORIES. 
ITS THE HOME PAGE BUT THEY CAN SET THE SECTION AVAILABLE AT ANYTIME THEY WANT
************************************************************************************ -->
	<looknfeel id="indexLook">
		<sections>
			<section id="s1">
				<heading>
					Nigeria Banking Sector
				</heading>
			
				<subcategoryLink>
					NncXWG_G
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
<!-- ******************************************************** -->

	<looknfeel id="newsLook">
		<sections>
			<section id="s1">
				<heading>
					On the news Yesterday
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
			
			<section id="s2">
				<heading>
					On the news Tomorrow
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
	
	<looknfeel id="newsSubcatLook">
		<sections>
			<section id="s1">
				<heading>
					On the news in the next hour
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
<!-- ******************************************************** -->

	<looknfeel id="sportsLook">
		<sections>
			<section id="s1">
				<heading>
					On the news NExt week
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
	
	<looknfeel id="sportsSubcatLook">
		<sections>
			<section id="s1">
				<heading>
					On the news in december
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
<!-- ******************************************************** -->

	<looknfeel id="businessLook">
		<sections>
			<section id="s1">
				<heading>
					On the news October
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
	
	<looknfeel id="businessSubcatLook">
		<sections>
			<section id="s1">
				<heading>
					On the news January
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
			
			<section id="s12">
				<heading>
					Reading article
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
<!-- ******************************************************** -->

	<looknfeel id="readArticleLook">
		<sections>
			<section id="s1">
				<heading>
					Reading article
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
			
			<section id="s2">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>

<!-- ******************************************************** -->
	<looknfeel id="lifeAndStyleLook">
		<sections>
			<section id="s1">
				<heading>
					Reading article
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
			
			<section id="s2">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s3">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s4">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s5">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s6">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s7">
				<heading>
					Dummy section
				</heading>
			
				<subcategoryLink>
					XXXXXXXX
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
	
	<!-- ******************************************************** -->
	<looknfeel id="lifeAndStyleSubcatLook">
		<sections>
			<section id="s1">
				<heading>
					Reading article
				</heading>
			
				<subcategoryLink>
					yhgg5678
				</subcategoryLink>
			</section>
			
			<section id="s2">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s3">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s4">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s5">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s6">
				<heading>
					On the world news
				</heading>
			
				<subcategoryLink>
					9098yhyt
				</subcategoryLink>
			</section>
			
			<section id="s7">
				<heading>
					Dummy section
				</heading>
			
				<subcategoryLink>
					XXXXXXXX
				</subcategoryLink>
			</section>
		</sections>
	</looknfeel>
</templates>

=== franklin-maduabueke/NewsCMS/life_and_style/food_and_drinks/food_and_drinks.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<templates xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com template.xsd"><looknfeel id="lifeAndStyleSubcatLook">
		<sections>
			<section id="s1">
				<heading>Fashion &amp; Style</heading>
			
				<subcategoryLink>QRo5SSHc</subcategoryLink>
			</section>
			
			<section id="s2">
				<heading>Relationships</heading>
			
				<subcategoryLink>NpwNcwDq</subcategoryLink>
			</section>
			
			<section id="s3">
				<heading>Africa</heading>
			
				<subcategoryLink>mSg6GRKw</subcategoryLink>
			</section>
			
			<section id="s4">
				<heading>Europe</heading>
			
				<subcategoryLink>iiqCu665</subcategoryLink>
			</section>
			
			<section id="s5">
				<heading>Asia</heading>
			
				<subcategoryLink>gR8EizAH</subcategoryLink>
			</section>
			
			<section id="s6">
				<heading>America</heading>
			
				<subcategoryLink>Pc1_SVp3</subcategoryLink>
			</section>
			
			<section id="s7">
				<heading>more from fashion &amp; style  around the world</heading>
			
				<subcategoryLink>Ib5P2DsM</subcategoryLink>
			</section>
		</sections>
	</looknfeel></templates>
